services:
  - type: web
    name: financial-health-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production